### PR TITLE
Bleed visuals

### PR DESCRIPTION
**Pull request by Flowaria**

### CODE REVIEW

**Comment by Flowaria** [comment]
Tested - Will merge immediately - Feel free to leave comment so I could fix on staging branch!

**Comment by liamqmacneil** [comment]
Would be cool if you could pick which screen liquid effect the bleed triggers

**Comment by dakkhuza** [comment]
Looks good to me, would be nice if you could change what screen liquid settings are used tho

**Comment by Flowaria** [comment]
> Looks good to me, would be nice if you could change what screen liquid settings are used tho

https://github.com/GTFO-Modding/ExtraEnemyCustomization/blob/956d700750d37471b6583b57a29530e432fe1b2b/ExtraEnemyCustomization/Customizations/Shared/BleedSetting.cs#L20
??

**Pull request merged**
