### PR TITLE
Rewrite on ConfigManager + Empty Default Configs now can be dumped

### PR DESCRIPTION
**Pull request by Flowaria**

### CODE REVIEW

**Review by Flowaria — COMMENTED** [review]
Looks fine for me

**Review by Panthr75 — COMMENTED** [review]
image
In Config.SetDefaultArrayPropertyValue, why is this commented out, and whats the purpose for this unnecessary finally clause

image
This patch adds will add the OnHotReloaded listener every time the rundown page gets enabled (which from the looks of it would also include switching to/from rundown page from the lobby screen). You could add a check to see if the listener was already applied, but there may be some caveats that I'm missing.

image
In ConfigManager.LoadConfig, you should use nameof instead of specifying the parameter by hand

image
In ConfigManager, you could in theory fetch these config types by using reflection, checking all types in your assembly, and filtering types that are non-abstract and are assignable to your base Config class

**Comment by Flowaria** [comment]
> In Config.SetDefaultArrayPropertyValue, why is this commented out, and whats the purpose for this unnecessary finally clause
> In ConfigManager.LoadConfig, you should use nameof instead of specifying the parameter by hand

Will be fixed on staging branch

> This patch adds will add the OnHotReloaded listener every time the rundown page gets enabled (which from the looks of it would also include switching to/from rundown page from the lobby screen). You could add a check to see if the listener was already applied, but there may be some caveats that I'm missing.

Will add additional check thanks!

> In ConfigManager, you could in theory fetch these config types by using reflection, checking all types in your assembly, and filtering types that are non-abstract and are assignable to your base Config class

I'll stick with manual writing for now as it could not filiter out unwanted types But I do have plan on do that

**Comment by Flowaria** [comment]
https://github.com/GTFO-Modding/ExtraEnemyCustomization/compare/7bcf81cb5819...ca44e41dec9c

**Comment by Flowaria** [comment]
Added Injected check to HotReloader inject
https://github.com/GTFO-Modding/ExtraEnemyCustomization/commit/b9c9bbc7589cb776d660c9006f3bb6906ebd84b1

**Pull request merged**
